"""empty message

Revision ID: b26f5e4aa513
Revises: aba47a7ee67a
Create Date: 2021-03-09 18:46:35.013228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b26f5e4aa513'
down_revision = 'aba47a7ee67a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'name')
    # ### end Alembic commands ###
