"""empty message

Revision ID: 30ff308674d0
Revises: dde61fddbcc1
Create Date: 2021-03-23 15:54:38.840804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30ff308674d0'
down_revision = 'dde61fddbcc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('options', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('options', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
